name: Home Assistant

on:
  push:
    branches:
      - master
  pull_request:

env:
  DEFAULT_PYTHON: 3.8

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v2"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
