name: Linting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_pytest:
    name: Run tests with pytest
    strategy:
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0

      - name: Install dependencies
        run: poetry install

      - name: Run alls tests with pytest
        run: |
          python -m pytest tests -v
